# Generated by Django 6.0.2 on 2026-07-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='linkedin_post_urn',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
